##########
services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: nginx.Dockerfile
    ports:
      - 443:443 # host port 443 binds to container port 443
    volumes:
      - ./requirements/nginx/certs:/etc/ssl/private
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf # substitutes existing .conf
    restart: on-failure # the policy restarts the container if the exit code indicates an error

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: wordpress.Dockerfile
    volumes:
      - ./requirements/wordpress/data:/var/www/html
    restart: on-failure

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: mariadb.Dockerfile
    environment:
      - MARIADB_ROOT_PASSWORD=supersecret-root-pw
      - MARIADB_DATABASE=DB
      - MARIADB_USER=mnegro
      - MARIADB_PASSWORD=supersecret-pw
    volumes:
      - mariadb_data:/var/lib/mysql # persist database data
    restart: on-failure

##########
volumes:
    wordpress_data:
    mariadb_data: # database setup more resilient and manageable

##########
networks:


##########
# volumes:
#   nginx_certs:
#     driver: local
#     driver_opts:
#       device: ./requirements/nginx/certs
#       o: bind
#       # used with `o: bind` to indicate that the mount is a bind and not a volume mount
#       type: none
#   wordpress_data:
#     driver: local
#     driver_opts:
#       device: ./requirements/wordpress/data
#       o: bind
#       type: none
##########
