# Version isn't needed as of 2020 for docker compose CLI
# All 2.x and 3.x features supported

services:
  nginx:
    container_name: gurghi_nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./requirements/nginx/conf/mnegro.42.fr.pem:/etc/ssl/certs/mnegro.42.fr.pem
      - ./requirements/nginx/conf/mnegro.42.fr.key:/etc/ssl/private/mnegro.42.fr.key
      - ./requirements/nginx/conf/server.conf:/etc/nginx/http.d/server.conf
      # - /home/mnegro/data/wp_data:/var/www/html/wordpress
      -  /Users/marzianegro/Desktop/wp_data:/var/www/html/wordpress
    depends_on:
      - wordpress
    restart: on-failure

  wordpress:
    container_name: gurghi_wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    env_file:
      - .env
    volumes:
    # - /home/mnegro/data/wp_data:/var/www/html/wordpress
      -  /Users/marzianegro/Desktop/wp_data:/var/www/html/wordpress
    depends_on:
      - mariadb
    restart: on-failure

  mariadb:
    container_name: gurghi_mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    env_file:
      - .env
    volumes:
    # - /home/mnegro/data/db_data:/var/lib/mysql
      -  /Users/marzianegro/Desktop/db_data:/var/lib/mysql
    restart: on-failure

##########

volumes:
    db_data:    
    wp_data:

##########

networks:
  default:
    name: gurghi_net
