services:
  nginx:
    container_name: gurghi_nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./requirements/nginx/conf/mnegro.42.fr.pem:/etc/ssl/certs/mnegro.42.fr.pem
      - ./requirements/nginx/conf/mnegro.42.fr.key:/etc/ssl/private/mnegro.42.fr.key
      - ./requirements/nginx/conf/server.conf:/etc/nginx/http.d/server.conf
      - wp_data:/var/www/html/wordpress
    restart: always

  wordpress:
    container_name: gurghi_wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html/wordpress
    depends_on:
      - mariadb
    restart: always

  mariadb:
    container_name: gurghi_mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    restart: always



volumes:
    # - /home/mnegro/data/db_data:
    db_data:
    # - /home/mnegro/data/wp_data:
    wp_data:



networks:
  default:
    name: gurghi_net
